# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da60edaa42322b44e6078b3ac2e143d923b1df7d4587241ffe13b81a87411931e567a2700620886641cda8dc93552118e9330372b967c04c8bd3485208cb1244

test:
  secret_key_base: f12d0e4580a95eba5542357e416d61edc9cd40608f52ea309de859eb47a2c385b2eab51a253f01a0922cf9ae9a43c17b9c256691575fc3f4295af4940ecfeb2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
